### ISSUE TITLE
A markdown file in this repository breaks bit-docs

### ISSUE THREAD

**Issue by leoj3n** [bit-docs/bit-docs-js#2]
The file in question is [`tags/module.md`](https://github.com/bit-docs/bit-docs-js/blob/master/tags/module.md):

```
PROCESSING: node_modules/bit-docs-js/tags/module.md
ERROR:
   tag - constructor
   line- @constructor documentjs.tags.module @module
/Users/leoj/bitovi/+/tempyo/tbd/bit-docs/node_modules/bit-docs-process-tags/process-tags.js:100
				throw e;
				^

TypeError: Cannot read property 'call' of undefined
    at module.exports (/Users/leoj/bitovi/+/tempyo/tbd/bit-docs/node_modules/bit-docs-process-tags/process-tags.js:95:28)
    at processFile (/Users/leoj/bitovi/+/tempyo/tbd/bit-docs/lib/process/file.js:71:3)
    at /Users/leoj/bitovi/+/tempyo/tbd/bit-docs/lib/process/process.js:88:5
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
```

I'm not entirely sure about all the intended syntax in that markdown file, so I've simply [ignored the `tags/module.md` file in bit-docs-website](https://github.com/bit-docs/bit-docs-website/commit/5bea1cc2837f576512cd059efcf482478d7ae569), instead of trying to rewrite that file for now.

Perhaps you can quickly fix that markdown file's syntax @justinbmeyer ? There's a couple of tags in there I've not seen before and am not sure if they are typos, or if they will be supported by bit-docs.

**Comment by leoj3n** [comment]
Hm. This doesn't seem to be causing an issue anymore; bit-docs is able to process this exact file when trying with a fresh copy of everything. Maybe this was related to something else in my setup.
